### ISSUE TITLE
Setting up initial and boundary conditions for flow past cylinder / airfoil

### ISSUE THREAD

**Issue by zonexo** [sciann/sciann#12]
Hi,

After reading the SciANN paper, I'm trying to set up my own case. 

I'm trying to solve flow past cylinder / airfoil, using the NS eqns. So, especially for the case of airfoil, how can I setup the boundary condition around the airfoil surface, which is u = v = 0?

Should I use the alternative approach mentioned in the paper?

Is there any example to follow?

Thank you.

**Comment by sciann** [comment]
If you want to impose a boundary condition, please follow the Burgers problem. You should pass `ids` of the sampling points where you want to impose a specific boundary condition.

**Comment by zonexo** [comment]
Hi, sorry for the delay. I have read your papers and looked into the Burgers problem.

From the paper, it mentions:

m = sn.SciModel ([t, x], [L1 , u], "mse", "Adam")

m.train([x_data,t_data],['zeros',(ids_ic_bc,U_ic_bc)],batch_size=256,epochs=10000)

I check and found that x_data and t_data are arrays of size (100,100).

But what is the array size of ids_ic_bc and U_ic_bc? Are they vectors or arrays? If ids_ic_bc are separated into ic and bc, is it right to say that ids_ic has a size of 100 (t = 0)?

Is ids_ic = [[0,0],[0,1],[0,2] .... ,[0,99]]? and U_ic is a vector = [0,-sin(pi*-0.979798), -sin(pi*-0.959596) .... 0]?

Thanks for the clarifications.

But
