### ISSUE TITLE
Importing SciANN Fails

### ISSUE THREAD

**Issue by NavyDevilDoc** [sciann/sciann#15]
Apologies for the trouble, but in Spyder 4.2 (through Anaconda), I get the following when trying to load SciANN using

`import sciann as sn`

![image](https://user-images.githubusercontent.com/79477977/108760424-a18ef700-751b-11eb-84f7-feb572c86ec8.png)

I downloaded the .zip file from GitHub and installed it through Anaconda's command window, but while the command line noted everything installed successfully, the attached error still occurs. As a basic remedial step, the previous copy was uninstalled and a new one downloaded/installed to no avail. Can I tell Python to not load the missing module? This is pretty much the extent of my knowledge with respect to troubleshooting these issues, so I haven't tried anything beyond remove/reinstall. 

Thank you very much for your time!

**Comment by NavyDevilDoc** [comment]
Apologies again, the versions of TensorFlow, Keras, and SciANN currently installed are:
 - TF: 2.1.0
 - Keras: 2.3.1
 - SciANN: 0.6.0.3

**Comment by sciann** [comment]
Can you test with TF>2.3>

**Comment by NavyDevilDoc** [comment]
Successfully updated to TF 2.4.1 but the problem still exists in the same form as the initial screenshot. Not sure if it matters, but when I look in the 'utils' folder, no module named 'transformers' was included. As a possible workaround, following the error chain given, I went into mlp_functional.py and commented out the `from ..utils.transformers import FourierFeature` line but that did not work either.

**Comment by sciann** [comment]
That is a bug - thanks for pointing this out. Not sure why I was not getting the error. It is now resolved. Please get the latest version:

`pip install --upgrade sciann `

**Comment by NavyDevilDoc** [comment]
I have a fully functioning SciANN!!! I have been looking forward to digging into the code alongside your paper and web documentation for a while now; thank you very much for making the fix so quickly!

**Comment by sciann** [comment]
Glad to hear that - thanks for the report.
