### ISSUE TITLE
Running SciModel causes error

### ISSUE THREAD

**Issue by midnight-prophet** [sciann/sciann#16]
Hi, 

I am just getting into SciANN and am looking to implement it to solve some PDEs. However I am getting some errors when just running your example code. The example code was taken from this page: https://www.sciann.com/getting-started/scimodel-guide/ 

This is with:
Jupyter Notebook 6.2.0
Python 3.6.12
Tensorflow 2.4.0
Keras 2.3.1
SciANN 0.6.0.4

![image](https://user-images.githubusercontent.com/67483352/109315843-e16b1c80-7842-11eb-9ca7-05099b3ab307.png)

I get the following ValueError when I set model = SciModel(cy)
ValueError: Please provide a `list` of `Variable` or `RadialBasis` objects for inputs.

**Comment by sciann** [comment]
Please check the documentation for the SciModel: https://www.sciann.com/scimodels/

You need to pass both the inputs (independent variables) and outputs (targets) to the SciModel. Here it should be: 

`model = SciModel(x, xy)`
