### ISSUE TITLE
How to set target-data when one functional variable have no training data avaliable?

### ISSUE THREAD

**Issue by YangZ2020** [sciann/sciann#22]
Hello, I'm trying the solid mechanics example of SciAnn.  (Script SciANN-SolidMechanics-BCs.py)
Interesting!
However, when I want to adopt only displacement boundary conditions on SciAnn, i.e., **stress component is totally unavaliable**, I'm in trouble with setting target_data (data_d3, and so on.). I tried leave data_d3 empty([], or np.array([])), However it doesn't work.

**Comment by ehsanhaghighat** [comment]
Hi Yang - in you don't have any condition on the stress, you should completely remove that from the targets.
