### ISSUE TITLE
Adaptive_weights = True raises error

### ISSUE THREAD

**Issue by mattiasutancykeln** [sciann/sciann#23]
When I try running the exact code found on https://www.sciann.com/examples/example-fitting-1d/, keras is raising a TypeError in utils/generic_utils.update(). How do you use the adaptive weights parameter?

**Comment by ehsanhaghighat** [comment]
What version of Keras/TF are you using?

**Comment by mattiasutancykeln** [comment]
Reinstalling tensorflow solved the issue
