### ISSUE TITLE
transfer learning

### ISSUE THREAD

**Issue by Alborz2020** [sciann/sciann#25]
I am going to use a pre-trained model (function) in new model structure. but I don't know how I can link the inputs to the old model. in keras we call the model, but I dont know how it goes with Sciann model. should we call the Function or Model?
best regards

**Comment by ehsanhaghighat** [comment]
hi - not clear what you want to achieve. can you share an example that you have done in Keras? 

in general, you can make any combination of functionals in SciANN. For instance:

```
x = sn.Variable(‘x’)
y = sn.Functioanl(‘y’, x, 4*[20], ’tanh’)
m1 = sn.SciModel(x, y)
m1.train(…) 

# Once trained you can make it not trainable: 
y.set_trainable(False)

#now you can go to the second model: 
z = sn.functional(‘z’, [x,y], 4*[20], ’tanh’)

# Input is still only x 
# If you now only like to train it on z, then target is only z. 
# the y functional is automatically evaluated at different xs, so you don’t need to do anything. 
m2 = sn.SciModel([x], [z]) 
m2.train(…)

```

**Comment by Alborz2020** [comment]
#Hello, thank you very much for your help and explanation. it is now clear for calling a pre-trained function we don't need any command to call the Function 'y' in new model.  
#  If I have to define a new function 'T', independent of 'y' while their summation forms a new function that will be used for automatic differentiation then it brings about a error.
# let me put it this way, for a pre-trained model as you mentioned:
x = sn.Variable(‘x’)
y = sn.Functioanl(‘y’, x, 4*[20], ’tanh’)
m1 = sn.SciModel(x, y)
m1.train(…)
######################
# if I define new function as:
z = sn.functional(‘z’, [x], 4*[20], ’tanh’)
# the Function T is defined as a summation of these two functions:
T = y + z
T_x = diff(T, x)
L1 = T_x
L2 = T
m2 = sn.SciModel(x,[L1,L2])

# it gets me following error:
_ValueError: Graph disconnected: cannot obtain value for tensor Tensor("x_11:0", shape=(None, 1), dtype=float32) at layer "concat_12". The following previous layers were accessed without issue: ['concat_29']_

# Am I doing sth wrong in between?


# Best reagrds,

**Comment by ehsanhaghighat** [comment]
This looks correct and it should work fine! 

Check our this google colab: https://colab.research.google.com/drive/1-L4cMpg08cK2QOzdye3NkziQ1uMAL_Yu?usp=sharing <https://colab.research.google.com/drive/1-L4cMpg08cK2QOzdye3NkziQ1uMAL_Yu?usp=sharing>

**Comment by Alborz2020** [comment]
thank you now it works for me as well. there was a tiny bug from my side.
