### ISSUE TITLE
The meaning of the data return by "get_weights" 

### ISSUE THREAD

**Issue by ZPLai** [sciann/sciann#39]
Dear community,

It is happy to meet SCIANN, such an amazing tool. I have a question need your patient help.

When I run following code:

f=sn.Functional(['f'],[u],[1],'linear')
weight_a=f.get_weights()
print(np.array(weight_a))
I get the below results, which is confused.

[[[-0.85555252525252]
   [0.00018264590427]
[[[-0.80343422342870]
   [0.00342918346589]]]

I think python should sent back 2 numbers for me, as I set 1 input, 1 output, and used 1 neural. While it sent back 4 numbers.
So what do these numers mean? And if I want to set specific weights and biases for a neuron, how should I do?

Thanks a lot

**Comment by ehsanhaghighat** [comment]
Thanks for your interest. The third argument of the Functional, i.e., [1], is the shape of hidden layer. To avoid having a hidden layer, pass `[]`.

**Comment by ZPLai** [comment]
> 

Thanks for reply.
I got it.
