### ISSUE TITLE
LBFGS optimizer not available

### ISSUE THREAD

**Issue by pradhyumna85** [sciann/sciann#47]
Is there any way to use LBFGS optimizer in SciANN ?

**Comment by ehsanhaghighat** [comment]
In scimodel, typye ‘optimizer=“scipy-****” Replace **** with your desired optimizer from scipy library On Aug 23, 2022, at 10:36 AM, Pradyumna Singh Rathore ***@***.***> wrote:﻿
Is there any way to use LBFGS optimizer in SciANN ?

**Comment by pradhyumna85** [comment]
Okay, that was helpful. But now the issue I observe is even though I am giving say 100 epochs in model.train, still the training stops training early after no loss change after some iterations, i.e., doesn't go till the epochs specified and I am not using any early stopping.

**Comment by ehsanhaghighat** [comment]
Yeah, scipy does its own thing although I pass epochs (max iterations). If you want to customize it, change the optimizer.py inside utils to follow your needs.

**Comment by pradhyumna85** [comment]
Ok Ehsan, thank you for the prompt response.
