### ISSUE TITLE
Google Collab Error. No attribute 'get_custom_objects' found. 

### ISSUE THREAD

**Issue by adxtop1** [sciann/sciann#80]
I got this error 2 days ago. Couldn't fix this till now. Before that everything used to work. 
I tried to change activation.py file. Still no luck. 
![Screenshot from 2023-02-15 22-42-44](https://user-images.githubusercontent.com/52373779/219102718-40a0d430-ba7c-4488-a151-c5f4b7683950.png)

module 'keras.utils.generic_utils' has no attribute 'get_custom_objects'

**Comment by ehsanhaghighat** [comment]
I hate how often TF/Keras change their interfaces - it is resolved now but not fun!
