### ISSUE TITLE
loss name meaning in the training history object

### ISSUE THREAD

**Issue by pradhyumna85** [sciann/sciann#81]
Hi,
what does the losses names mean like: epoch_mul_<some_number>_loss
And how they relate to the PDE losses/constraints ?

**Comment by ehsanhaghighat** [comment]
Same order as you define targets in SciModel.You can rename your losses for better names: L1 = sn.rename(L1, “my_fav_name”)On Feb 23, 2023, at 8:06 AM, Pradyumna Singh Rathore ***@***.***> wrote:﻿
Hi,
what does the losses names mean like: epoch_mul_<some_number>_loss
And how they relate to the PDE losses/constraints ?

**Comment by pradhyumna85** [comment]
Thank you @ehsanhaghighat.
