### ISSUE TITLE
Activation with trainable parameter

### ISSUE THREAD

**Issue by pradhyumna85** [sciann/sciann#82]
Hi,
How to use activation with trainable parameter?

**Comment by ehsanhaghighat** [comment]
Add l- before the loss name:  “l-tanh” On Feb 23, 2023, at 8:07 AM, Pradyumna Singh Rathore ***@***.***> wrote:﻿
Hi,
How to use activation with trainable parameter?

**Comment by pradhyumna85** [comment]
Thank you @ehsanhaghighat.
