### ISSUE TITLE
BFGS/L-BFGS optimizers

### ISSUE THREAD

**Issue by iamcalvinlau** [sciann/sciann#9]
It doesn't seem like Keras currently has any BFGS/L-BFGS optimizers, and the way to use those optimizers "normally" is to wrap tf_probability (tf 2+) or with tf.contrib.opt.ScipyOptimizerInterface (tf 1.x). Is there any plan to implement those wraparounds in the SciANN package?

**Comment by ehsanhaghighat** [comment]
It is actually under testing and will be released soon.

**Comment by ehsanhaghighat** [comment]
Good news - in the latest release, you can pick a scipy optimizer. 
This is not a final, well-tested version, so expect bugs in addition to the performance difference. 

`SciModel(..., optimizer="scipy-L-BFGS-B")`

You can also pick other scipy optimizers. Let me know if you tried it out.
