### ISSUE TITLE
values not updating after every epoch

### ISSUE THREAD

**Issue by adxtop1** [sciann/sciann#90]
Is there any way i could update the values of parameter more frequently in INVERSE PROBLEM of PINN? For my problem, for every 1k epoch i can see only 6 values of Lambda over the history. I want the value of Lambda of after each epoch.

**Comment by ehsanhaghighat** [comment]
do you mean frequency of adaptive weights? you can use (e.g.):
>> {‘method’: ‘GP’, ‘freq’: 5}

**Comment by adxtop1** [comment]
Yess frequency
